service: serverless-test
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  deploymentMethod: direct
  iam:
    role: arn:aws:iam::494763483344:group/esl_serverless_group
  stage: staging
  timeout: 30
  vpcEndpointIds:
    # - vpce-0a00abf9092369fc1
    - vpce-064a45101e31828f6
  vpc:
    securityGroupIds:
      # - sg-08fdf3242146c1302
      - sg-0ff745bb07160886c
    subnetIds:
      # - subnet-0efad544c3737c15b
      - subnet-08e1de5cc781b1775 

functions:
  test_1:
    handler: handler.greet
    role: arn:aws:iam::494763483344:role/esl_serverless_lambda
    url:
      cors: true
  test_2:
    # Private api (access from vpc only)
    handler: handler.hello
    role: arn:aws:iam::494763483344:role/esl_serverless_lambda
    url:
      cors: true
    events:
      - httpApi: '*'
