service: esl-testapp
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  deploymentMethod: direct
  iam:
    role: arn:aws:iam::494763483344:group/esl_serverless_group
  stage: staging
  timeout: 30
  endpointType: PRIVATE
  # PROD
  # vpcEndpointIds:
  #   - vpce-064a45101e31828f6
  vpc:
    securityGroupIds:
      - sg-0ff745bb07160886c
    subnetIds:
      - subnet-08e1de5cc781b1775

functions:
  # Private api (IP whitelisted)
  test_1:
    handler: handler.greet
    role: arn:aws:iam::494763483344:role/esl_serverless_lambda
    url:
      cors: true
    events:
      - httpApi: '*'
      # Override vpc config to allow access from a specific IP
    vpc:
      securityGroupIds:
        - sg-04af4c4a11a37028f
      subnetIds:
        - subnet-08e1de5cc781b1775
  test_2:
   # Private api (access from vpc only)
    handler: handler.hello
    role: arn:aws:iam::494763483344:role/esl_serverless_lambda
    url:
      cors: true
    events:
      - httpApi: '*'
    # Override vpc config for this function. Create a security group to only allow inbound requests from the vpc
    vpc:
      securityGroupIds:
        - sg-0a37b1b933590e192
      subnetIds:
        - subnet-08e1de5cc781b1775
      
